### ISSUE TITLE
Problem restoring summed like object generated with version fermi_beta associated to python 2.7

### ISSUE THREAD

**Issue by landriu** [fermi-lat/pyLikelihood#19]

**Comment by landriu** [comment]
When testing fit on a summed like object with another spectrum type, and getting back the initial 
object using :
    saved_state = LikelihoodState(summed_like)
and later : 
    for srcNameEach in summed_like.sourceNames():
        saved_state.restore(srcNameEach)

we get the following error when asking for : 
summed_like.Ts( PSRJ0835-4510 ) : 

 File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/SummedLikelihoo
d.py", line 278, in Ts
    comp.logLike.setFreeParamValues(freeParams)
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/pyLikelihood.py
", line 2834, in setFreeParamValues
    return _pyLikelihood.Function_setFreeParamValues(self, paramVec)
RuntimeError: Function::setFreeParamValues: The input vector size 5  does not match 6 , the number of free parameters.
.../...

I provide a compressed file including a script reproducing this problem, and the needed files
to run it on the temporary area , where it should be availlable two weeks: 
     ftp://ftp.cea.fr/incoming/y2k01/testRestore

Ask me if you do not find it.

Thanks for your help

**Comment by jballet** [comment]
The report refers to Fermi Tools 1.3.1

**Comment by landriu** [comment]
Hello,

  in fact the test can be simplified as the problem also occurs when restoring after
small modifications plus fit the summed_like object, so I have built another simpler
test from the initial script : 

  I have put the input files, the script testRestore.py and the logs in another ftp target : 

 ftp:/ftp.cea.fr/incoming/y2k01/testRestore/testRestore1.tgz

Let me now, if you need more information

Cheers,

 David

PS: new test script : 

#!/usr/bin/env python
#

from SummedLikelihood import *
from BinnedAnalysis import *
from LikelihoodState import LikelihoodState
                                  
# -- -- -- -- -- -- -- -- 

# Build summed like model and apply fit with original spectrum type :
summed_like = SummedLikelihood()

myconf = BinnedConfig(edisp_bins=-1)

obs = BinnedObs( irfs="CALDB", expCube="LiveTimeCube_4.fits", 
            srcMaps="srcMap_4_E1.fits", binnedExpMap="binned_exposure_E1.fits") 
like = BinnedAnalysis(obs,"srcModel_4.xml-initial",optimizer="Minuit", 
            config=myconf)

summed_like.addComponent(like)

obs = BinnedObs( irfs="CALDB", expCube="LiveTimeCube_4.fits", 
            srcMaps="srcMap_4_E3.fits", binnedExpMap="binned_exposure_E3.fits") 
like = BinnedAnalysis(obs,"srcModel_4.xml-initial",optimizer="Minuit", 
            config=myconf)

summed_like.addComponent(like)
srcName = 'PSRJ0835-4510'

summed_like.fit()

print "summed_like.Ts(",srcName,"):",summed_like.Ts(srcName)

SpectrumType = like.model[srcName].src.spectrum().genericName()

saved_state = LikelihoodState(summed_like)

spmodel = summed_like.model[srcName].funcs['Spectrum']

print "spmodel:",spmodel
 
#x # -- Apply fit with PowerLaw model :
#x 
#x summed_like.setSpectrum( srcName, 'PowerLaw' )
#x 
#x indx = summed_like.par_index(srcName, 'Scale')
#x summed_like[indx] = 500
#x  
#x indx = summed_like.par_index(srcName, 'Index')
#x summed_like[indx].setBounds(-5,0)
#x  
#x indx = summed_like.par_index(srcName, 'Prefactor')
#x print 'summed_like[indx] :',summed_like[indx].getValue()
#x  
#x summed_like[indx].setBounds(0,100)
#x summed_like[indx].setScale(2e-9)

TabIndx = []

indx = summed_like.par_index(srcName, 'alpha')
TabIndx.append(indx)
summed_like[indx] = 5
 
indx = summed_like.par_index(srcName, 'beta')
TabIndx.append(indx)
summed_like[indx].setBounds(-5,5)
 
spmodel = summed_like.model[srcName].funcs['Spectrum']

print "spmodel:",spmodel
 
summed_like.freeze(TabIndx)
summed_like.fit()
summed_like.thaw(TabIndx)

# --

print "summed_like.Ts(",srcName,") for powerLaw :",summed_like.Ts( srcName )

# Go back to previous model :
summed_like.setSpectrum( srcName, SpectrumType)

for srcNameEach in summed_like.sourceNames():
  saved_state.restore(srcNameEach)

print "\nsummed_like.model:",summed_like.model

print "summed_like.Ts(",srcName,") for",SpectrumType,":",summed_like.Ts(srcName)

print "summed_like.NpredValue(",srcName,"):",summed_like.NpredValue(srcName)

**Comment by landriu** [comment]
This issue is still open, sorry for the bad button choice.

**Comment by landriu** [comment]
After some researches, we have found that using summed_like.SyncParams() before the
like.Ts() avoid the error, but the resulting value is different from the result produced 
with the official version  : 

new values : 

  summed_like.Ts( PSRJ0835-4510 ) : 1394.8527347 
  summed_like.NpredValue( PSRJ0835-4510 ): 417.666986723

current values obtained with official version : 

  summed_like.Ts( PSRJ0835-4510 ) : 1414.3879308 
  summed_like.NpredValue( PSRJ0835-4510 ): 417.666986723

**Comment by jballet** [comment]
I may add a bit of context to explain when this happens in the Catalog pipeline.
We systematically test, for each source, an alternative spectral shape to the main one (eg, if the source is LogParabola, we test PowerLaw; if the source is PowerLaw, we test LogParabola or PLSuperExpCutoff, depending on whether it is a pulsar or not).
If the curved alternative is significantly better than the original PowerLaw, or the PowerLaw is nearly as good as the original curved spectral shape, we adopt the alternative and we refit again the full model.
But in most cases the original model is all right so we revert to the original best fit by using the saved_state.restore facility. Then we compute the final TS (with reoptimize = Y).
Up to FT 1.2.23 this worked fine.
At 1.3.1 this does not work any more. It would possibly work if we did an additional fit before the TS calls, but it is a useless calculation because we already did it before.

**Comment by jasercion** [comment]
Update: 

The place where the error seems to be introduced appears to be the `summed_like.setSpectrum( srcName, SpectrumType)` call in the script.  If this is commented out the restoration appears to run to completion however the resulting values are similar to the new values @landriu reported above. 

Just to make sure I'm thinking of this correctly, the correct number of free parameters for the summed_like object _should_ be 5 right?  As directly inherited from the initial xml model?

**Comment by jballet** [comment]
Yes, after the intermediate modifications the model at the end should be back to what it was at the beginning, with 5 free parameters (2 for diffuse, and 3 for the LogParabola spectrum).

**Comment by dagorym** [comment]
Well, I've tracked down the location of the problem, if not the exact cause.  It comes from an update Eric made (in April) in the optimizers::Parameter class and then changed some code in the _Parameter wrapper class in the LikelihoodState.py file to call it.  Reverting LikelihoodState.py to the old code solves this problem but I suspect it will reintroduce whatever problem Eric was trying to fix. The commit message on optimizers for the change was:  "Added setDataValue member to paramter to deal with reseting the saved state without messing up nested parameters."

It looks like an issue with deep vs. shallow copies and those nested parameters but I need to do some more poking and get a better understanding of the code.  This is literally the first time I've ever looked at the likelihood and optimizers code other that some superficial peeks following recipes to add support for new spectral models.  I'm still figuring out how the code works.

**Comment by dagorym** [comment]
Okay, I have fixed this with the pull request listed above.  Here is what was happening:

The Parameter class that is part of the SummedLikelihood class, maintains a list of the parameter values for each of the components.  However, when the LikelihoodState object is created, it saves out one set of values (from the first component).  Then when it restores it, in only updates the first component of the parameter, and doens't touch the later ones.

This means that in the Ts() method, which removes and adds the source to the model, the recreated source, which has all the parameters free for all the components, runs into trouble when trying to set the parameter values for the later components as the LikelihoodState.restore() method only gets the correct update applied to the first component.

I've updated the LikelihoodState.restore() method to check for the case where there is more than one component and copy the saved parameter values to all the components.  The supplied test case now passes as does the earlier test case for Likelihood issue #76 (https://github.com/fermi-lat/Likelihood/issues/76),

Note, I'm just copying the saved values from the first component into all of them.  However, since that is all the Ts() method in the SummedLikelihood class is doing anyway with the values stored there, I assumed that was sufficient.  If we need to save all the separate values from all the separate components, that will be a lot more work and may require a major restructuring of the code to handle the various possible cases of likelihood objects that can be passed into the LikelhoodState object.

**Comment by jballet** [comment]
This is OK. In the SummedLikelihood approach the parameters MUST be the same for all components.

**Comment by donhorner** [comment]
@landriu @jballet Can someone confirm that this has been fixed in the latest beta?

**Comment by landriu** [comment]
Hi Don,

   I have launched the test script with new beta  fermi-1.3.5, and got the values we had before changes : 

(fermi-1.3.5) 
[landriu@sappcfermi] ~/dev/testFermi_beta/simple-with-1.3.5 > python testRestore.py 
.../...
summed_like.Ts( PSRJ0835-4510 ) for LogParabola : 1414.38864911
summed_like.NpredValue( PSRJ0835-4510 ): 417.662303023
(fermi-1.3.5) 

  So it has been fixed indeed, and I close this issue.
